const langMap = {
  en: {
    year: {
      previous: 'last year',
      current: 'this year',
      next: 'next year',
      past: '{0} years ago',
      future: 'in {0} years',
    },
    quarter: {
      previous: 'last quarter',
      current: 'this quarter',
      next: 'next quarter',
      past: '{0} quarters ago',
      future: 'in {0} quarters',
    },
    month: {
      previous: 'last month',
      current: 'this month',
      next: 'next month',
      past: '{0} months ago',
      future: 'in {0} months',
    },
    week: {
      previous: 'last week',
      current: 'this week',
      next: 'next week',
      past: '{0} weeks ago',
      future: 'in {0} weeks',
    },
    day: {
      previous: 'yesterday',
      current: 'today',
      next: 'tomorrow',
      past: '{0} days ago',
      future: 'in {0} days',
    },
    hour: {
      previous: '{0} hour ago',
      current: 'this hour',
      next: 'in {0} hour',
      past: '{0} hours ago',
      future: 'in {0} hours',
    },
    minute: {
      previous: '{0} minute ago',
      current: 'this minute',
      next: 'in {0} minute',
      past: '{0} minutes ago',
      future: 'in {0} minutes',
    },
    second: {
      previous: '{0} second ago',
      current: 'now',
      next: 'in {0} second',
      past: '{0} seconds ago',
      future: 'in {0} seconds',
    },
  },
  zh: {
    year: {
      previous: '去年',
      current: '今年',
      next: '明年',
      past: '{0}年前',
      future: '{0}年后',
    },
    quarter: {
      previous: '上季度',
      current: '本季度',
      next: '下季度',
      past: '{0}个季度前',
      future: '{0}个季度后',
    },
    month: {
      previous: '上个月',
      current: '本月',
      next: '下个月',
      past: '{0}个月前',
      future: '{0}个月后',
    },
    week: {
      previous: '上周',
      current: '本周',
      next: '下周',
      past: '{0}周前',
      future: '{0}周后',
    },
    day: {
      previous: '昨天',
      previous2: '前天',
      current: '今天',
      next: '明天',
      next2: '后天',
      past: '{0}天前',
      future: '{0}天后',
    },
    hour: {
      previous: '{0}小时前',
      current: '此时',
      next: '小时后',
      past: '{0}小时前',
      future: '{0}小时后',
    },
    minute: {
      previous: '{0}分钟前',
      current: '此刻',
      next: '小时后',
      past: '{0}秒钟后',
      future: '{0}分钟后',
    },
    second: {
      previous: '{0}秒钟前',
      current: '现在',
      past: '{0}秒钟后',
      next: '小时后',
      future: '{0}秒钟后',
    },
  },
};

export default langMap;
